batch_size: 16
lambda: 10
checkpoint_base: checkpoints
samples_path: samples
save_every: 100
resume: ""
seed: 0
use_cuda: False
dataset_path: "../data/sc_simulated_data.npy"
dis_iters: 5
epochs: 5000

models:
    generator:
        fn: generator.py
        z_slow_dim: 256
        z_fast_dim: 256
        out_channels: 1
        bottom_width: 4
        conv_ch: 512

    discriminator:
        fn: discriminator.py
        name: TemporalDiscriminator
        in_channels: 1
        mid_ch: 62
