lambda: 10
checkpoint_base: checkpoints
samples_path: samples
save_every: 100
resume: ""
seed: 0
use_cuda: False
dataset_path: "../data/sc_simulated_data.npy"
dis_iters: 5
epochs: 5000

z_slow_dim: 128
z_fast_dim: 128
genes_num: 1000
time_points: 8
batch_size: 64

models:
    generator:
        fn: generator.py


    discriminator:
        fn: discriminator.py
        name: TemporalDiscriminator
        in_channels: 1
        mid_ch: 62
